name: Django CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-20.04
    services:
      postgres:
        image: postgres
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: mysitedb
        ports:
          - 5432:5432
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5
        
    steps:
      - name: Checkout code
        uses: actions/checkout@v2   
      - name: Setup python environment
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'
      - name: Install Dependencies
        run: 
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Collectstatic
        run: python manage.py collectstatic
      - name: Run Tests
        run: python manage.py test
